apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-app
spec:
  selector:
    matchLabels:
      run: resource-app
  template:
    metadata:
      labels:
        run: resource-app
    spec:
      containers:
      - name: resource-app
        image: ireshmm/resource:2
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: resource-app
  labels:
    run: resource-app
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    run: resource-app
