services:
  web:
    image: ireshmm/resource:2
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: main.py
    restart: always
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app